# Generated by Django 6.0.5 on 2026-05-08 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', 'V20260508_154056_607_0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', 'V20260508_154056_628_0002_initial'),
        ('user', 'V20260508_154056_679_0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='user.tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='rbac_users', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='userapiblock',
            name='api_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation'),
        ),
        migrations.AddField(
            model_name='userapiblock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='userapiblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='core.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dwerp_users', to='user.tenant'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userapiblock',
            index=models.Index(fields=['tenant', 'user', 'api_operation'], name='idx_user_api_block_main'),
        ),
        migrations.AlterUniqueTogether(
            name='userapiblock',
            unique_together={('tenant', 'user', 'api_operation')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'tenant', 'role'], name='idx_userrole_user_tenant_role'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='idx_userrole_role'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_role'),
        ),
    ]
