# Generated by Django 6.0.5 on 2026-05-08 10:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('master_app', 'V20260508_154056_659_0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('code', models.CharField(db_index=True, help_text='Name (2-50 characters)', max_length=50, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Name must be at least 2 characters long')])),
                ('name', models.TextField()),
                ('status', models.TextField(default='active')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dwerp_tenant',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Account active/suspended status')),
                ('is_staff', models.BooleanField(default=False, help_text='Staff access flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.CharField(blank=True, max_length=255, null=True)),
                ('email_verification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('password_reset_sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_plan_purchased', models.BooleanField(default=False)),
                ('role_id', models.BigIntegerField(blank=True, null=True)),
                ('invited_by_id', models.UUIDField(blank=True, null=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_failed_login', models.DateTimeField(blank=True, null=True)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='dwerp_users', to='auth.group')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_users', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='dwerp_users', to='auth.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant')),
            ],
            options={
                'db_table': 'dwerp_user',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dwerp_refreshtoken',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('resource', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='success', max_length=50)),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tenant')),
            ],
            options={
                'db_table': 'auditlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='logout', max_length=50)),
            ],
            options={
                'db_table': 'token_blacklist',
                'indexes': [models.Index(fields=['user_id', 'revoked_at'], name='token_black_user_id_a02361_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('phone_type', models.CharField(choices=[('mobile', 'Mobile'), ('office', 'Office'), ('home', 'Home'), ('other', 'Other')], default='mobile', max_length=30)),
                ('object_id', models.PositiveIntegerField()),
                ('is_primary', models.BooleanField(default=False)),
                ('is_whatapp', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant')),
            ],
            options={
                'db_table': 'contact_details',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='contact_det_content_4af2ca_idx'), models.Index(fields=['tenant', 'is_active', 'is_deleted'], name='contact_det_tenant__24640b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address_type', models.CharField(choices=[('site', 'Site'), ('billing', 'Billing'), ('shipping', 'Shipping'), ('office', 'Office'), ('architect', 'Architect'), ('customer', 'Customer'), ('lead_contact', 'Lead Contact'), ('project_site', 'Project Site'), ('headquarter', 'Headquarter'), ('permanent', 'Permanent')], default='customer', max_length=90)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.mstcity')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.mstcountry')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_app.mststate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant')),
            ],
            options={
                'db_table': 'address_details',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='address_det_content_1f5315_idx'), models.Index(fields=['tenant', 'created_at'], name='address_det_tenant__f3c985_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['tenant', 'email'], name='dwerp_user_tenant__f43f08_idx'),
        ),
        migrations.AddIndex(
            model_name='usermodel',
            index=models.Index(fields=['tenant', 'is_deleted', 'is_active'], name='dwerp_user_tenant__5120a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('email', 'tenant_id'), name='unique_email_per_tenant_active'),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('username', 'tenant_id'), name='unique_username_per_tenant_active'),
        ),
    ]
