services:
 db:
   image: postgres:15
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
     - "${DB_PORT}:${DB_PORT}"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env
 
 web:
   build: .
   container_name: django-docker
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     ALLOWED_HOSTS: ${ALLOWED_HOSTS}
     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_HOST: ${DB_HOST}
     DB_PORT: ${DB_PORT}
   env_file:
     - .env
volumes:
   postgres_data: