# Generated by Django 5.0.6 on 2026-05-06 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin_api_details',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_module',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_role',
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_sub_module',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenant',
            },
        ),
        migrations.CreateModel(
            name='ApiOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('http_method', models.CharField(max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('permission_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apiendpoint')),
            ],
            options={
                'db_table': 'admin_api_operation',
            },
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.module'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.module')),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'admin_permission',
            },
        ),
        migrations.CreateModel(
            name='ModuleSubModuleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='core.module')),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submodule')),
            ],
            options={
                'db_table': 'admin_mod_submodule_mapping',
            },
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'admin_role_permission_mapping',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.CreateModel(
            name='TenantApiOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('api_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'admin_tenant_api_operation',
            },
        ),
        migrations.CreateModel(
            name='TenantApiPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('api_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'db_table': 'admin_tenant_api_permission',
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.module')),
                ('submodule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.tenant')),
            ],
            options={
                'db_table': 'admin_tenant_module',
            },
        ),
        migrations.AddIndex(
            model_name='apioperation',
            index=models.Index(fields=['http_method', 'is_active', 'is_deleted'], name='idx_apiop_method_active'),
        ),
        migrations.AddIndex(
            model_name='apioperation',
            index=models.Index(fields=['endpoint', 'http_method'], name='idx_apiop_endpoint_method'),
        ),
        migrations.AlterUniqueTogether(
            name='apioperation',
            unique_together={('endpoint', 'http_method')},
        ),
        migrations.AlterUniqueTogether(
            name='modulesubmodulemapping',
            unique_together={('module', 'submodule')},
        ),
        migrations.AddIndex(
            model_name='apiendpoint',
            index=models.Index(fields=['path'], name='idx_apiendpoint_path'),
        ),
        migrations.AddIndex(
            model_name='apiendpoint',
            index=models.Index(fields=['is_active', 'is_deleted'], name='idx_apiendpoint_active'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'allowed', 'tenant'], name='idx_roleperm_tenant_allow'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='idx_roleperm_permission'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_active', 'is_deleted'], name='idx_role_tenant_active'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_perm_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module', 'submodule'], name='idx_perm_module_submodule'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'module', 'submodule', 'code')},
        ),
        migrations.AddIndex(
            model_name='tenantapioverride',
            index=models.Index(fields=['tenant', 'api_operation', 'is_enabled'], name='idx_tenant_api_override'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantapioverride',
            unique_together={('tenant', 'api_operation')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantapipermission',
            unique_together={('tenant', 'api_operation')},
        ),
        migrations.AddIndex(
            model_name='tenantmodule',
            index=models.Index(fields=['tenant', 'is_enabled'], name='idx_tenant_module_enabled'),
        ),
        migrations.AddConstraint(
            model_name='tenantmodule',
            constraint=models.UniqueConstraint(fields=('tenant', 'module', 'submodule'), name='unique_tenant_module_submodule'),
        ),
    ]
