# Generated by Django 6.0.5 on 2026-05-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', 'V20260508_154056_619_0001_initial'),
        ('user', 'V20260508_154056_679_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='permission',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.AddField(
            model_name='modulesubmodulemapping',
            name='submodule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.AddField(
            model_name='tenantapioverride',
            name='api_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation'),
        ),
        migrations.AddField(
            model_name='tenantapioverride',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='tenantapipermission',
            name='api_operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.apioperation'),
        ),
        migrations.AddField(
            model_name='tenantapipermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permission'),
        ),
        migrations.AddField(
            model_name='tenantapipermission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.module'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='submodule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.submodule'),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='user.tenant'),
        ),
        migrations.AddIndex(
            model_name='apioperation',
            index=models.Index(fields=['http_method', 'is_active', 'is_deleted'], name='idx_apiop_method_active'),
        ),
        migrations.AddIndex(
            model_name='apioperation',
            index=models.Index(fields=['endpoint', 'http_method'], name='idx_apiop_endpoint_method'),
        ),
        migrations.AlterUniqueTogether(
            name='apioperation',
            unique_together={('endpoint', 'http_method')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant', 'is_active', 'is_deleted'], name='idx_role_tenant_active'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'allowed', 'tenant'], name='idx_roleperm_tenant_allow'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission'], name='idx_roleperm_permission'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_perm_tenant_active'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module', 'submodule'], name='idx_perm_module_submodule'),
        ),
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together={('tenant', 'module', 'submodule', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='modulesubmodulemapping',
            unique_together={('module', 'submodule')},
        ),
        migrations.AddIndex(
            model_name='apiendpoint',
            index=models.Index(fields=['path'], name='idx_apiendpoint_path'),
        ),
        migrations.AddIndex(
            model_name='apiendpoint',
            index=models.Index(fields=['is_active', 'is_deleted'], name='idx_apiendpoint_active'),
        ),
        migrations.AddIndex(
            model_name='tenantapioverride',
            index=models.Index(fields=['tenant', 'api_operation', 'is_enabled'], name='idx_tenant_api_override'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantapioverride',
            unique_together={('tenant', 'api_operation')},
        ),
        migrations.AlterUniqueTogether(
            name='tenantapipermission',
            unique_together={('tenant', 'api_operation')},
        ),
        migrations.AddIndex(
            model_name='tenantmodule',
            index=models.Index(fields=['tenant', 'is_enabled'], name='idx_tenant_module_enabled'),
        ),
        migrations.AddConstraint(
            model_name='tenantmodule',
            constraint=models.UniqueConstraint(fields=('tenant', 'module', 'submodule'), name='unique_tenant_module_submodule'),
        ),
    ]
