# Generated by Django 6.0.5 on 2026-05-08 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_app', 'V20260508_154056_659_0001_initial'),
        ('user', 'V20260508_154056_679_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mstproduct',
            name='tenant',
            field=models.ForeignKey(help_text='Tenant identifier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.tenant'),
        ),
        migrations.AddField(
            model_name='mstproducttype',
            name='product',
            field=models.ForeignKey(help_text='Parent product', on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='master_app.mstproduct'),
        ),
        migrations.AddField(
            model_name='mstproducttype',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant identifier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.tenant'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforcutbarcodeduplicatescan',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_reason__is_acti_54b703_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforcutbarcodeduplicatescan',
            index=models.Index(fields=['sequence_no'], name='mst_reason__sequenc_9e67de_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforenquirycancel',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_reason__is_acti_21c6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforenquirycancel',
            index=models.Index(fields=['sequence_no'], name='mst_reason__sequenc_b3e686_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforquotationcancelled',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_reason__is_acti_d911c7_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforquotationcancelled',
            index=models.Index(fields=['sequence_no'], name='mst_reason__sequenc_532808_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforreprintjobmaterialbarcode',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_reason__is_acti_7808df_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreasonforreprintjobmaterialbarcode',
            index=models.Index(fields=['sequence_no'], name='mst_reason__sequenc_065909_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreceiveat',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_receive_is_acti_26239d_idx'),
        ),
        migrations.AddIndex(
            model_name='mstreceiveat',
            index=models.Index(fields=['sequence_no'], name='mst_receive_sequenc_1cdc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='mstscantype',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_scan_ty_is_acti_c4e42f_idx'),
        ),
        migrations.AddIndex(
            model_name='mstscantype',
            index=models.Index(fields=['sequence_no'], name='mst_scan_ty_sequenc_b066fd_idx'),
        ),
        migrations.AddIndex(
            model_name='mststagemaster',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_stage_m_is_acti_e9ac12_idx'),
        ),
        migrations.AddIndex(
            model_name='mststagemaster',
            index=models.Index(fields=['sequence_no'], name='mst_stage_m_sequenc_1fd5df_idx'),
        ),
        migrations.AddField(
            model_name='mststate',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Associated country for this state', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.mstcountry'),
        ),
        migrations.AddField(
            model_name='mstcity',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Associated state for this city', null=True, on_delete=django.db.models.deletion.CASCADE, to='master_app.mststate'),
        ),
        migrations.AddIndex(
            model_name='mststatus',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_status_is_acti_d68a79_idx'),
        ),
        migrations.AddIndex(
            model_name='mststatus',
            index=models.Index(fields=['sequence_no'], name='mst_status_sequenc_f4cd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='mststatus',
            index=models.Index(fields=['display_text'], name='mst_status_display_604f92_idx'),
        ),
        migrations.AddIndex(
            model_name='msttaxtype',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_tax_typ_is_acti_d2462f_idx'),
        ),
        migrations.AddIndex(
            model_name='msttaxtype',
            index=models.Index(fields=['sequence_no'], name='mst_tax_typ_sequenc_f808c5_idx'),
        ),
        migrations.AddField(
            model_name='msttax',
            name='tax_type',
            field=models.ForeignKey(blank=True, help_text='Tax category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tax_details', to='master_app.msttaxtype'),
        ),
        migrations.AddIndex(
            model_name='msttitle',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_title_is_acti_f3f589_idx'),
        ),
        migrations.AddIndex(
            model_name='mstuom',
            index=models.Index(fields=['is_active', 'created_at'], name='mstUOM_is_acti_e41066_idx'),
        ),
        migrations.AddIndex(
            model_name='mstuom',
            index=models.Index(fields=['symbol'], name='mstUOM_symbol_507a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='mstverifieraction',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_verifie_is_acti_18a800_idx'),
        ),
        migrations.AddIndex(
            model_name='mstverifieraction',
            index=models.Index(fields=['sequence_no'], name='mst_verifie_sequenc_240935_idx'),
        ),
        migrations.AddIndex(
            model_name='mstverifieractionpaymentreceipt',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_verifie_is_acti_6b9b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='mstverifieractionpaymentreceipt',
            index=models.Index(fields=['sequence_no'], name='mst_verifie_sequenc_794b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='mstcountry',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_country_is_acti_96c713_idx'),
        ),
        migrations.AddIndex(
            model_name='mstpaymenttermsmilestones',
            index=models.Index(fields=['payment_term', 'is_active'], name='mst_payment_Payment_e1c844_idx'),
        ),
        migrations.AddIndex(
            model_name='mstpaymenttermsmilestones',
            index=models.Index(fields=['status'], name='mst_payment_StatusI_ca3064_idx'),
        ),
        migrations.AddIndex(
            model_name='mstpaymenttermsmilestones',
            index=models.Index(fields=['days'], name='mst_payment_days_1152e9_idx'),
        ),
        migrations.AddIndex(
            model_name='mstpaymenttermsmilestones',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_payment_is_acti_ec872f_idx'),
        ),
        migrations.AddIndex(
            model_name='mstproduct',
            index=models.Index(fields=['tenant', 'is_active', '-created_at'], name='mst_product_tenant__147a4a_idx'),
        ),
        migrations.AddIndex(
            model_name='mstproduct',
            index=models.Index(fields=['tenant', 'code'], name='mst_product_tenant__065417_idx'),
        ),
        migrations.AddConstraint(
            model_name='mstproduct',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_product_code_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='mstproducttype',
            index=models.Index(fields=['tenant', 'is_active', '-created_at'], name='mst_product_tenant__e9951d_idx'),
        ),
        migrations.AddIndex(
            model_name='mstproducttype',
            index=models.Index(fields=['tenant', 'product', 'code'], name='mst_product_tenant__00f625_idx'),
        ),
        migrations.AddConstraint(
            model_name='mstproducttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'product', 'code'), name='uniq_product_type_code_per_tenant_product'),
        ),
        migrations.AddIndex(
            model_name='mststate',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_state_is_acti_299dca_idx'),
        ),
        migrations.AddIndex(
            model_name='mststate',
            index=models.Index(fields=['country_id'], name='mst_state_country_36e81b_idx'),
        ),
        migrations.AddIndex(
            model_name='mstcity',
            index=models.Index(fields=['is_active', 'created_at'], name='mst_city_is_acti_7caa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='mstcity',
            index=models.Index(fields=['state_id'], name='mst_city_state_i_91ed51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mstcity',
            unique_together={('name', 'state')},
        ),
        migrations.AddIndex(
            model_name='msttax',
            index=models.Index(fields=['is_active'], name='mst_tax_is_acti_ae097e_idx'),
        ),
        migrations.AddIndex(
            model_name='msttax',
            index=models.Index(fields=['code'], name='mst_tax_code_39235d_idx'),
        ),
    ]
