# """
# Django settings for CommonAdminService project.

# Generated by 'django-admin startproject' using Django 6.0.4.

# For more information on this file, see
# https://docs.djangoproject.com/en/6.0/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/6.0/ref/settings/
# """


# from pathlib import Path
# from CommonAdminService.migration_naming_patch import *
# from decouple import config,Csv
# import os
# from CommonAdminService import auto_create_migration_dirs as acmd

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# DYNAMIC_LOG_PATH = os.path.join(BASE_DIR, "Logs")

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = config('SECRET_KEY')
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config('DEBUG', default=False, cast=bool)
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'msbc_rbac',
#     'msbc_rbac.core',
#     'msbc_rbac.accounts',
#     'drf_spectacular',
#     'rest_framework',
#     'rest_framework.authtoken',
#     'msbc_json_config_engine.apps',
#     'msbc_json_config_engine.config',
# ]


# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#         'CommonAdminService.middleware.HTTPLoggingMiddleware',
# ]


# EXTRA_MIDDLEWARE  = config("MIDDLEWARE", default="", cast=Csv())



# MIDDLEWARE = MIDDLEWARE + EXTRA_MIDDLEWARE

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console': {
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'WARNING',
#     },
# }
# REST_FRAMEWORK = {
#     'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.TokenAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
# }


# SPECTACULAR_SETTINGS = {
#     'TITLE': 'CommanAdminService',
#     'DESCRIPTION': 'Multi-tenant RBAC + ABAC API',
#     'VERSION': '1.0.0',
#     'SERVE_INCLUDE_SCHEMA': False,
#     'SECURITY': [
#         {'tokenAuth': []},
#         {'cookieAuth': []},
#     ],
#     'APPEND_COMPONENTS': {
#         'securitySchemes': {
#             'tokenAuth': {
#                 'type': 'apiKey',
#                 'in': 'header',
#                 'name': 'Authorization',
#                 'description': 'Token-based authentication. Format: `Token <your-token-here>`'
#             },
#             'cookieAuth': {
#                 'type': 'apiKey',
#                 'in': 'cookie',
#                 'name': 'sessionid',
#                 'description': 'Session-based authentication (existing)'
#             }
#         }
#     },
# }
# ROOT_URLCONF = 'CommonAdminService.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'CommonAdminService.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/6.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# # STATICFILES_DIRS = [
# #     os.path.join(BASE_DIR, 'static'),
# # ]


# AUTH_USER_MODEL = config("USER_MODEL", default=None)
# TENANT_MODEL = config('TENANT_MODEL', default=None)

# assert AUTH_USER_MODEL, "Auth User not provided"
# assert TENANT_MODEL, "Tenant not provided"

# AUTHORITATIVE_SCHEMA_SERVICE = acmd.AUTHORITATIVE_SCHEMA_SERVICE
# acmd.ensure_migration_dirs()
# MIGRATION_MODULES = acmd.get_migration_modules()



"""
Django settings for CommonAdminService project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path
from CommonAdminService.migration_naming_patch import *
from decouple import config,Csv
import os
from CommonAdminService import auto_create_migration_dirs as acmd
 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
DYNAMIC_LOG_PATH = os.path.join(BASE_DIR, "Logs")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'msbc_rbac',
    'msbc_rbac.core',
    'msbc_rbac.accounts',
    'drf_spectacular',
    'rest_framework',
    'rest_framework.authtoken',
    'msbc_json_config_engine.apps.config_engine',
    'common_models_service.dwerp.master_app', # adding common_models_service here also because of runtime error
]

EXTERNAL_APPS = config('EXTERNAL_INSTALLED_APP', default=[], cast = Csv())
print(EXTERNAL_APPS , "EXTERNAL_APPS")
INSTALLED_APPS += EXTERNAL_APPS
print(INSTALLED_APPS, "Installed_app")


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'CommonAdminService.middleware.HTTPLoggingMiddleware',
]


EXTRA_MIDDLEWARE  = config("MIDDLEWARE", default="", cast=Csv())

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = MIDDLEWARE + EXTRA_MIDDLEWARE

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


SPECTACULAR_SETTINGS = {
    'TITLE': 'CommanAdminService',
    'DESCRIPTION': 'Multi-tenant RBAC + ABAC API',
    'VERSION': '1.0.0',
    'SWAGGER_UI_SETTINGS': {
    'persistAuthorization': True,
    },

    'SERVE_INCLUDE_SCHEMA': False,
    'SECURITY': [
        {'tokenAuth': []},
        {'cookieAuth': []},
    ],
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'tokenAuth': {
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
                'description': 'Token-based authentication. Format: `Token <your-token-here>`'
            },
            'cookieAuth': {
                'type': 'apiKey',
                'in': 'cookie',
                'name': 'sessionid',
                'description': 'Session-based authentication (existing)'
            }
        }
    },
}
ROOT_URLCONF = 'CommonAdminService.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'CommonAdminService' / 'core' / 'json_v1' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CommonAdminService.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]


AUTH_USER_MODEL = config("USER_MODEL", default=None)
TENANT_MODEL = config('TENANT_MODEL', default=None)

assert AUTH_USER_MODEL, "Auth User not provided"
assert TENANT_MODEL, "Tenant not provided"


AUTHORITATIVE_SCHEMA_SERVICE = acmd.AUTHORITATIVE_SCHEMA_SERVICE
acmd.ensure_migration_dirs()
MIGRATION_MODULES = acmd.get_migration_modules()